import { memeBase64 } from "./meme";
import { Resvg, initWasm } from "@resvg/resvg-wasm";
// @ts-ignore
import resvgWasm from "@resvg/resvg-wasm/index_bg.wasm";

function getOrdinal(d: number) {
	if (d > 3 && d < 21) return 'th';
	switch (d % 10) {
		case 1: return "st";
		case 2: return "nd";
		case 3: return "rd";
		default: return "th";
	}
}

function formatText(ms: number, tz: string): string {
	let d: number;
	let mLong: string;
	let mShort: string;
	try {
		d = parseInt(new Intl.DateTimeFormat('en-US', { day: 'numeric', timeZone: tz }).format(ms));
		mLong = new Intl.DateTimeFormat('en-US', { month: 'long', timeZone: tz }).format(ms);
		mShort = new Intl.DateTimeFormat('en-US', { month: 'short', timeZone: tz }).format(ms);
	} catch {
		tz = 'UTC';
		d = parseInt(new Intl.DateTimeFormat('en-US', { day: 'numeric', timeZone: tz }).format(ms));
		mLong = new Intl.DateTimeFormat('en-US', { month: 'long', timeZone: tz }).format(ms);
		mShort = new Intl.DateTimeFormat('en-US', { month: 'short', timeZone: tz }).format(ms);
	}
	
	const ordinal = getOrdinal(d);
	const fullLong = `${mLong} ${d}${ordinal}`;
	if (fullLong.length > 11) {
		return `${mShort} ${d}${ordinal}`;
	}
	return fullLong;
}

let wasmInitialized = false;
let fontData: Uint8Array | null = null;
const fontUrl = "https://fonts.gstatic.com/s/roboto/v51/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjammT.ttf"; // Roboto Bold TTF

export default {
	async fetch(request: Request, env: any, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url);
		const tz = url.searchParams.get("tz") || "UTC";

		const cacheKey = new Request(url.toString(), request);
		const cache = caches.default;
		
		let response = await cache.match(cacheKey);
		if (response) {
			return response;
		}

		if (!wasmInitialized) {
			try {
				await initWasm(resvgWasm);
				wasmInitialized = true;
			} catch (e) {
				wasmInitialized = true;
			}
		}

		if (!fontData) {
			const fontRes = await fetch(fontUrl);
			fontData = new Uint8Array(await fontRes.arrayBuffer());
		}

		const nowMs = Date.now();
		const tomorrowMs = nowMs + 24 * 60 * 60 * 1000;
		
		const todayText = formatText(nowMs, tz);
		const tomorrowText = formatText(tomorrowMs, tz);
		
		const host = request.headers.get("host") || "example.com";

		const svg = `
<svg width="968" height="1291" viewBox="0 0 968 1291" xmlns="http://www.w3.org/2000/svg">
  <style>
    .bold-text {
      font-family: 'Roboto';
      font-weight: bold;
      font-size: 56px;
      fill: black;
    }
    .credit {
      font-family: 'Roboto';
      font-size: 26px;
      fill: #b4b4b4;
    }
  </style>

  <image href="data:image/jpeg;base64,${memeBase64}" width="968" height="1291" />

  <rect x="322" y="115" width="330" height="81" rx="15" fill="white" />
  <text x="487" y="176" class="bold-text" text-anchor="middle">${todayText}</text>

  <rect x="65" y="1035" width="342" height="81" rx="15" fill="white" />
  <text x="236" y="1096" class="bold-text" text-anchor="middle">${tomorrowText}</text>

  <text x="956" y="1279" class="credit" text-anchor="end">Generated by ${host}</text>
</svg>
`.trim();

		const resvg = new Resvg(svg, {
			font: {
				fontBuffers: [fontData!],
				loadSystemFonts: false,
				defaultFontFamily: 'Roboto'
			}
		});

		const pngData = resvg.render();
		const pngBuffer = pngData.asPng();

		response = new Response(pngBuffer, {
			headers: {
				"Content-Type": "image/png",
				"Access-Control-Allow-Origin": "*",
				"Cache-Control": "public, s-maxage=3600, max-age=60" 
			}
		});
		
		ctx.waitUntil(cache.put(cacheKey, response.clone()));
		
		return response;
	},
};
